In [1]:
import numpy as np
x=np.array([2,5,8])
print(x)
print(x.shape)

[2 5 8]
(3,)


In [9]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,3,7],[5,0,2]])
print(A)
print(A.shape)
print(A.T)
print(A.T.shape)
print(A+B)
x=np.array([2,3,4])
print(A)
print(A*x)
print(A*B)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
[[ 2  5 10]
 [ 9  5  8]]
[[1 2 3]
 [4 5 6]]
[[ 2  6 12]
 [ 8 15 24]]
[[ 1  6 21]
 [20  0 12]]
